name: API Tests # 界面名称
#触发条件
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
  #公共测试
    runs-on: ubuntu-latest #运行环境
    #检查代码
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  #设置python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
#安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/req.txt   # 依赖文件名，按实际路径修改
#运行测试
    - name: Run tests
      run: |
        cd config   # 进入测试文件所在目录
        pytest -v --html=report.html --self-contained-html
#上传报告
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: config/report.html
#仓库测试
  warehouse-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies for warehouse_tests
        run: |
          python -m pip install --upgrade pip
          cd warehouse_tests
          pip install -r requirements.txt
      - name: Run warehouse tests
        run: |
          cd warehouse_tests
          pytest tests/ -v --html=report_warehouse.html --self-contained-html
      - name: Upload warehouse report
        uses: actions/upload-artifact@v4
        with:
          name: warehouse-report
          path: warehouse_tests/report_warehouse.html
